### ISSUE TITLE
Error in Hangfire job

### ISSUE THREAD

**Issue by mattspeterson** [mattspeterson/myjongg#168]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at MyJongg.Models.CardOfHands.MatchingHands(IEnumerable`1 playerRack, IEnumerable`1 playerExposedSets) in C:\projects\myjongg\Models\Cards\CardOfHands.cs:line 70
   at MyJongg.Models.CardOfHands.FindBestHands(IEnumerable`1 playerRack, IEnumerable`1 playerExposedSets, Int32 numberOfHandsToFind) in C:\projects\myjongg\Models\Cards\CardOfHands.cs:line 51
   at MyJongg.Models.CardOfHands.FindBestHand(IEnumerable`1 playerRack, IEnumerable`1 playerExposedSets) in C:\projects\myjongg\Models\Cards\CardOfHands.cs:line 40
   at MyJongg.Models.Game.RemovePlayer(String connectionId, String& message) in C:\projects\myjongg\Models\Game.cs:line 378
   at MyJongg.Models.GameService.<>c__DisplayClass7_1.<PurgeExpiredLimboPlayers>b__2(Player player) in C:\projects\myjongg\Models\GameService.cs:line 87
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at MyJongg.Models.GameService.PurgeExpiredLimboPlayers() in C:\projects\myjongg\Models\GameService.cs:line 87
```

**Comment by mattspeterson** [comment]
Stopped getting this...I think https://github.com/mattspeterson/myjongg/commit/237ee6d285b40f72e82ab49052e6c0a28cfd10dd or https://github.com/mattspeterson/myjongg/commit/8c01267f8981281395adfe8beff3b9c2887fa69c fixed it.
